server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_URL_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

