server:
  address: 0.0.0.0
  port: 8080

spring:
  profiles:
    include: local, jwt, oauth

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

chromedriver:
  path: ${CHROMEDRIVER_PATH}

management:
  endpoint:
    health:
      show-details: never
  health:
    db:
      enabled: false

cloud:
  aws:
    s3:
      bucket: loopz-bucket
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:test-region}
      auto: false
    stack:
      auto: false

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION:1800000}
    refresh: ${REFRESH_EXPIRATION:2592000000}
  secret: ${JWT_SECRET:test1234tes1tte2st1234test1te!stte7stt@#e4sttes5ttest2testtest1234123415215161231}

kakao:
  oauth:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    frontend-redirect-uri: ${KAKAO_FRONTEND_REDIRECT_URI}


firebase:
  secret-key-path: firebase/firebaseAccountKey.json
