server:
  port: 8080

spring:
  profiles:
    include: local, jwt, oauth

  datasource:
    url: jdbc:mysql://${DB_URL_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

chromedriver:
  path: ${CHROMEDRIVER_PATH}

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION:1800000}
    refresh: ${REFRESH_EXPIRATION:2592000000}
  secret: ${JWT_SECRET:test1234tes1tte2st1234test1te!stte7stt@#e4sttes5ttest2testtest1234123415215161231}

kakao:
  oauth:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    frontend-redirect-uri: ${KAKAO_FRONTEND_REDIRECT_URI}


firebase:
  secret-key-path: firebase/firebaseAccountKey.json
