server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_URL_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect